import { Suspense, useEffect, useRef } from 'react'
import { Canvas } from '@react-three/fiber'
import { AdaptiveDpr, PerformanceMonitor } from '@react-three/drei'
import { SolarSystem } from '../components/3d/SolarSystem'
import { useSimulationStore } from '../store/simulationStore'
import { clamp } from '../utils/random'
import type { QualityLevel } from '../types'

/** Lowest to highest. Automatic changes stay inside this range. */
const QUALITY_ORDER: QualityLevel[] = ['low', 'medium', 'high']

/**
 * The look the app was designed around, and the highest tier the automatic
 * monitor may reach: a faster machine than we expected does not need a different
 * picture, it needs the same one at a higher frame rate. 'high' stays a
 * deliberate choice in Settings.
 */
const DEFAULT_QUALITY: QualityLevel = 'medium'

/**
 * The first seconds of a WebGL scene are always slow — shaders compile and
 * procedural textures upload on the first frames — so performance decisions taken
 * then say nothing about the machine. Ignoring them prevents a capable computer
 * from being downgraded (and left looking dark) because of its own start-up.
 */
const WARM_UP_MS = 5000

/**
 * The WebGL scene.
 *
 * Everything expensive (textures, geometry) is already generated by the time
 * this mounts, so the canvas appears fully formed. `PerformanceMonitor` watches
 * the frame rate and steps the quality down when it stays low — never during the
 * start-up warm-up, never below the default look, and never permanently: a
 * machine that proves comfortable steps back up. `AdaptiveDpr` trims the pixel
 * ratio before geometry detail is sacrificed.
 */
export function SolarSystemScene() {
  const quality = useSimulationStore((state) => state.quality)
  const setQuality = useSimulationStore((state) => state.setQuality)
  const warmUpUntil = useRef(0)

  useEffect(() => {
    warmUpUntil.current = performance.now() + WARM_UP_MS
  }, [])

  const stepQuality = (direction: 1 | -1): void => {
    const current = useSimulationStore.getState().quality
    const ceiling = QUALITY_ORDER.indexOf(DEFAULT_QUALITY)
    const next = QUALITY_ORDER[clamp(QUALITY_ORDER.indexOf(current) + direction, 0, ceiling)]
    if (next === current) return
    setQuality(next)
    // Say so out loud: an unexplained change of lighting is exactly what makes a
    // quality drop feel like a bug.
    if (direction === -1) {
      useSimulationStore.getState().showToast('Slowing the graphics down a little to keep the motion smooth.', 'info')
    }
  }

  const handleDecline = (): void => {
    if (performance.now() < warmUpUntil.current) return
    stepQuality(-1)
  }

  // The monitor also reports an *incline* when the machine is comfortably fast,
  // which lets a downgrade be undone instead of lasting for the whole session.
  const handleIncline = (): void => stepQuality(1)

  return (
    <Canvas
      className="sse-canvas"
      dpr={quality === 'low' ? [0.8, 1.3] : [1, 1.75]}
      camera={{ position: [18, 44, 96], fov: 48, near: 0.1, far: 6000 }}
      gl={{
        antialias: quality === 'low',
        powerPreference: 'high-performance',
        alpha: false,
        stencil: false,
      }}
      onCreated={({ gl }) => {
        gl.setClearColor('#03050d')
      }}
    >
      {/* Deliberately no onFallback. The monitor counts an incline as a flip too,
          so even a comfortably fast machine reaches its fallback after a few
          windows: it only means "stop changing your mind", not "this device is
          hopeless". Treating it as the latter used to slam the scene to the
          lowest tier — and with it the bloom, most of the stars and part of the
          lighting — a few seconds after the scene appeared. */}
      <PerformanceMonitor onDecline={handleDecline} onIncline={handleIncline} flipflops={3}>
        <Suspense fallback={null}>
          <SolarSystem quality={quality} />
        </Suspense>
        <AdaptiveDpr pixelated />
      </PerformanceMonitor>
    </Canvas>
  )
}